### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by DiyaPrabhuram** [SindiLab/ACTINN-PyTorch#2]
Where can I find the requirements.txt file? I didn't see it anywhere in this repo

**Comment by dr-aheydari** [comment]
Hi @DiyaPrabhuram ! Sorry for the late response, for some reason I did not get a notification for this issue.

`requirements.txt` had been stashed, but now I have added it to the repo : ) `setup.py` should also have the same requirements as the `requirements.txt`.

Please let me know if you have any other issues with the package/code. Also, please feel free to directly mention me so that way I am notified :)

Best,
Ali
